# Generated by Django 3.0.8 on 2020-08-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200806_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='due_date',
            field=models.DateField(blank=True, help_text='Deadline', null=True),
        ),
    ]
