# Generated by Django 3.0.8 on 2020-08-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='reference_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
