# Generated by Django 3.0.8 on 2020-08-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_reference_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='priority',
            new_name='ticket_type',
        ),
        migrations.AlterField(
            model_name='project',
            name='reference_link',
            field=models.URLField(blank=True, help_text='include protocol, eg: "https://example.com"', null=True),
        ),
    ]
