# Generated by Django 3.0.8 on 2020-08-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200807_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='severity',
            field=models.CharField(choices=[('None', 'None'), ('Show Stopper', 'Show Stopper'), ('Critical', 'Critical'), ('Major', 'Major'), ('Minor', 'Minor')], default='None', max_length=15),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('Crash/Hang', 'Crash/Hang'), ('UI/Usability', 'UI/Usability'), ('Bug/Error', 'Bug/Error'), ('Security', 'Security'), ('Feature Request', 'Feature Request'), ('Other Comments', 'Other Comments'), ('Training/Document Requests', 'Training/Document Requests')], max_length=27),
        ),
    ]
