# Generated by Django 3.0.8 on 2020-08-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20200807_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('A', 'Administrator'), ('M', 'Project Manager'), ('D', 'Developer'), ('S', 'Submitter')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('IP', 'In Progress'), ('OT', 'On Track'), ('DL', 'Delayed'), ('TE', 'In Testing'), ('HO', 'On Hold'), ('AP', 'Approved'), ('CN', 'Cancelled'), ('PL', 'Planning'), ('CM', 'Completed'), ('IN', 'Invoiced')], default='AC', max_length=2),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='severity',
            field=models.CharField(choices=[('NO', 'None'), ('SS', 'Show Stopper'), ('CR', 'Critical'), ('MJ', 'Major'), ('MI', 'Minor')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Closed'), ('P', 'In Progress'), ('R', 'Resolved'), ('I', 'Additional Info Required')], max_length=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('CH', 'Crash/Hang'), ('UI', 'UI/Usability'), ('BG', 'Bug/Error'), ('SQ', 'Security'), ('FR', 'Feature Request'), ('OC', 'Other Comments')], max_length=2),
        ),
    ]
