# Generated by Django 3.0.8 on 2020-08-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20200808_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Project Manager', 'Project Manager'), ('Developer', 'Developer'), ('Submitter', 'Submitter')], default='Submitter', max_length=16),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('In Progress', 'In Progress'), ('On Track', 'On Track'), ('Delayed', 'Delayed'), ('In Testing', 'In Testing'), ('On Hold', 'On Hold'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled'), ('Planning', 'Planning'), ('Completed', 'Completed'), ('Invoiced', 'Invoiced')], default='Active', max_length=25),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='severity',
            field=models.CharField(choices=[('None', 'None'), ('Show Stopper', 'Show Stopper'), ('Critical', 'Critical'), ('Major', 'Major'), ('Minor', 'Minor')], default='None', max_length=15),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Additional Info Required', 'Additional Info Required')], max_length=24),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('Crash/Hang', 'Crash/Hang'), ('UI/Usability', 'UI/Usability'), ('Bug/Error', 'Bug/Error'), ('Security', 'Security'), ('Feature Request', 'Feature Request'), ('Other Comments', 'Other Comments'), ('Training/Document Requests', 'Training/Document Requests')], max_length=27),
        ),
    ]
