# Generated by Django 3.0.8 on 2020-08-09 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_portal'),
        ('projects', '0016_remove_project_portal'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Portal'),
        ),
    ]
