# Generated by Django 3.0.8 on 2020-08-10 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Member'),
        ),
    ]
