# Generated by Django 3.0.8 on 2020-08-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_milestone_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
