# Generated by Django 3.0.8 on 2020-08-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_milestone_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milestone',
            old_name='end_date',
            new_name='due_date',
        ),
        migrations.AddField(
            model_name='milestone',
            name='completed_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
