# Generated by Django 3.0.8 on 2020-08-12 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20200810_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='reference_link',
            field=models.URLField(blank=True, help_text='include http protocol; eg: "https://example.com"', null=True),
        ),
    ]
