# Generated by Django 3.0.8 on 2020-08-17 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_portal'),
        ('projects', '0023_auto_20200812_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('Administrator', 'Administrator'), ('Project Manager', 'Project Manager'), ('Developer', 'Developer'), ('Submitter', 'Submitter')], default='Submitter', max_length=16)),
                ('verified', models.BooleanField(default=False)),
                ('expiry', models.DateTimeField()),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Portal')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
