# Generated by Django 3.0.8 on 2020-08-21 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_milestone_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='milestone',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='MilestoneComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('file', models.ImageField(blank=True, null=True, upload_to='')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Member')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Milestone')),
            ],
        ),
    ]
