# Generated by Django 3.0.8 on 2020-08-21 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20200821_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestonecomment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
