# Generated by Django 3.0.8 on 2020-08-24 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_portal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0029_auto_20200822_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='portal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Portal'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='portal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Portal'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=25),
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Member')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Ticket')),
            ],
        ),
    ]
