# Generated by Django 3.0.8 on 2020-09-22 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_auto_20200824_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestonecomment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='ticketcomment',
            name='image',
        ),
    ]
