# Generated by Django 3.0.8 on 2020-08-30 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20200829_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='project_group',
            new_name='project_chat_group',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user_group',
            new_name='user_chat_group',
        ),
    ]
