# Generated by Django 3.0.8 on 2020-09-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_auto_20200830_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectchatgroup',
            name='name',
            field=models.CharField(default='default', help_text='Fills automatically. Same as project title', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userchatgroup',
            name='name',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
    ]
