# Generated by Django 3.0.8 on 2020-09-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_auto_20200901_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectchatgroup',
            name='room_type',
            field=models.CharField(choices=[('PG', 'Project Group'), ('UG', 'User Group'), ('PC', 'Private Chat')], default='PG', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userchatgroup',
            name='room_type',
            field=models.CharField(choices=[('PG', 'Project Group'), ('UG', 'User Group'), ('PC', 'Private Chat')], default='UG', max_length=2),
            preserve_default=False,
        ),
    ]
