# Generated by Django 3.0.8 on 2020-09-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='target_type',
            field=models.CharField(blank=True, choices=[('PG', 'Project Group'), ('UG', 'User Group'), ('PC', 'Private Chat')], max_length=2, null=True),
        ),
    ]
