# Generated by Django 3.0.8 on 2020-09-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_message_target_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='target_type',
            field=models.CharField(choices=[('PG', 'Project Group'), ('UG', 'User Group'), ('PC', 'Private Chat')], max_length=2),
        ),
    ]
