# Generated by Django 3.0.8 on 2020-09-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_auto_20200915_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('S', 'Sent'), ('D', 'Delivered'), ('R', 'Read'), ('F', 'Failed')], default='S', max_length=1),
        ),
    ]
