# Generated by Django 3.0.8 on 2020-09-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_message_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='id_on_client',
            field=models.CharField(blank=True, help_text='Temporary ID on client', max_length=36, null=True),
        ),
    ]
