# Generated by Django 3.0.8 on 2020-09-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0012_auto_20200916_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_type',
            field=models.CharField(blank=True, choices=[('D', 'Document'), ('A', 'Audio'), ('V', 'Video'), ('I', 'Image')], max_length=1),
        ),
    ]
