# Generated by Django 3.0.8 on 2020-09-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0013_message_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file_type',
            field=models.CharField(blank=True, choices=[('application', 'Document'), ('audio', 'Audio'), ('video', 'Video'), ('image', 'Image')], max_length=11, null=True),
        ),
    ]
