# Generated by Django 3.0.8 on 2020-09-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0014_auto_20200920_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='message',
            name='file_type',
            field=models.CharField(blank=True, choices=[('application', 'Document'), ('audio', 'Audio'), ('video', 'Video'), ('image', 'Image')], editable=False, max_length=11, null=True),
        ),
    ]
