# Generated by Django 3.0.8 on 2020-09-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0015_auto_20200922_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectchatgroup',
            name='room_type',
            field=models.CharField(blank=True, choices=[('PG', 'Project Group'), ('UG', 'User Group'), ('PC', 'Private Chat')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='userchatgroup',
            name='room_type',
            field=models.CharField(blank=True, choices=[('PG', 'Project Group'), ('UG', 'User Group'), ('PC', 'Private Chat')], max_length=2, null=True),
        ),
    ]
